///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TAU_Selenium_WebDriver
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BlankFields recording.
    /// </summary>
    [TestModule("dc1972ac-8c02-45f4-9682-b9fb7055c229", ModuleType.Recording, 1)]
    public partial class BlankFields : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TAU_Selenium_WebDriverRepository repository.
        /// </summary>
        public static TAU_Selenium_WebDriverRepository repo = TAU_Selenium_WebDriverRepository.Instance;

        static BlankFields instance = new BlankFields();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BlankFields()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BlankFields Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://inkubit.com/en-us/#' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://inkubit.com/en-us/#", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Contact' at 40;26.", repo.INKUBITMicrosoftDynamics365CRMCon.ContactInfo, new RecordItemIndex(2));
            repo.INKUBITMicrosoftDynamics365CRMCon.Contact.Click("40;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.FirstName' at 131;16.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.FirstNameInfo, new RecordItemIndex(3));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.FirstName.Click("131;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.LastName' at 89;21.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.LastNameInfo, new RecordItemIndex(4));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.LastName.Click("89;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddress' at 87;26.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddressInfo, new RecordItemIndex(5));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddress.Click("87;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.Message' at 84;28.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.MessageInfo, new RecordItemIndex(6));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.Message.Click("84;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.SEND' at 43;22.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.SENDInfo, new RecordItemIndex(7));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.SEND.Click("43;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Please fill First Name field') on item 'INKUBITMicrosoftDynamics365CRMCon.FirstNameError'.", repo.INKUBITMicrosoftDynamics365CRMCon.FirstNameErrorInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.FirstNameErrorInfo, "InnerText", "Please fill First Name field");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='LastName-error') on item 'INKUBITMicrosoftDynamics365CRMCon.LastNameError'.", repo.INKUBITMicrosoftDynamics365CRMCon.LastNameErrorInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.LastNameErrorInfo, "Id", "LastName-error");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Please fill Surname') on item 'INKUBITMicrosoftDynamics365CRMCon.LastNameError'.", repo.INKUBITMicrosoftDynamics365CRMCon.LastNameErrorInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.LastNameErrorInfo, "InnerText", "Please fill Surname");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='EmailAddress-error') on item 'INKUBITMicrosoftDynamics365CRMCon.EmailAddressError'.", repo.INKUBITMicrosoftDynamics365CRMCon.EmailAddressErrorInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.EmailAddressErrorInfo, "Id", "EmailAddress-error");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Required Field') on item 'INKUBITMicrosoftDynamics365CRMCon.EmailAddressError'.", repo.INKUBITMicrosoftDynamics365CRMCon.EmailAddressErrorInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.EmailAddressErrorInfo, "InnerText", "Required Field");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Message-error') on item 'INKUBITMicrosoftDynamics365CRMCon.MessageError'.", repo.INKUBITMicrosoftDynamics365CRMCon.MessageErrorInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.MessageErrorInfo, "Id", "Message-error");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Required Field') on item 'INKUBITMicrosoftDynamics365CRMCon.MessageError'.", repo.INKUBITMicrosoftDynamics365CRMCon.MessageErrorInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.MessageErrorInfo, "InnerText", "Required Field");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'INKUBITMicrosoftDynamics365CRMCon'.", repo.INKUBITMicrosoftDynamics365CRMCon.SelfInfo, new RecordItemIndex(15));
            Host.Current.KillApplication(repo.INKUBITMicrosoftDynamics365CRMCon.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
