///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TAU_Selenium_WebDriver
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FormFieldValidationWrongEmail recording.
    /// </summary>
    [TestModule("3f6bac90-f065-4300-b4c7-fa1a9e0726af", ModuleType.Recording, 1)]
    public partial class FormFieldValidationWrongEmail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TAU_Selenium_WebDriverRepository repository.
        /// </summary>
        public static TAU_Selenium_WebDriverRepository repo = TAU_Selenium_WebDriverRepository.Instance;

        static FormFieldValidationWrongEmail instance = new FormFieldValidationWrongEmail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FormFieldValidationWrongEmail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FormFieldValidationWrongEmail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://bioptron-gdansk.pl/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://bioptron-gdansk.pl/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.ElementorElementElementorElementB35a' at 265;61.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.ElementorElementElementorElementB35aInfo, new RecordItemIndex(2));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.ElementorElementElementorElementB35a.Click("265;61");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Next}{Next}{Next}' with focus on 'BioptronZepterGdanskBioptronZepter'.", repo.BioptronZepterGdanskBioptronZepter.SelfInfo, new RecordItemIndex(3));
            repo.BioptronZepterGdanskBioptronZepter.Self.EnsureVisible();
            Keyboard.Press("{Next}{Next}{Next}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1' at 62;22.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1Info, new RecordItemIndex(4));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1.Click("62;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tom' with focus on 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1'.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1Info, new RecordItemIndex(5));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1.PressKeys("tom");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField2' at 64;28.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField2Info, new RecordItemIndex(6));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField2.Click("64;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '3838383' with focus on 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField2'.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField2Info, new RecordItemIndex(7));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField2.PressKeys("3838383");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.FormFieldName' at 324;12.", repo.BioptronZepterGdanskBioptronZepter.FormFieldNameInfo, new RecordItemIndex(8));
            repo.BioptronZepterGdanskBioptronZepter.FormFieldName.Click("324;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sub' with focus on 'BioptronZepterGdanskBioptronZepter.FormFieldName'.", repo.BioptronZepterGdanskBioptronZepter.FormFieldNameInfo, new RecordItemIndex(9));
            repo.BioptronZepterGdanskBioptronZepter.FormFieldName.PressKeys("sub");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.FormFieldMessage' at 288;34.", repo.BioptronZepterGdanskBioptronZepter.FormFieldMessageInfo, new RecordItemIndex(10));
            repo.BioptronZepterGdanskBioptronZepter.FormFieldMessage.Click("288;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'quest' with focus on 'BioptronZepterGdanskBioptronZepter.FormFieldMessage'.", repo.BioptronZepterGdanskBioptronZepter.FormFieldMessageInfo, new RecordItemIndex(11));
            repo.BioptronZepterGdanskBioptronZepter.FormFieldMessage.PressKeys("quest");
            Delay.Milliseconds(2170);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
