///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TAU_Selenium_WebDriver
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FormValidation recording.
    /// </summary>
    [TestModule("4a769d4d-5213-4e7b-835d-5de7d68ba3fe", ModuleType.Recording, 1)]
    public partial class FormValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TAU_Selenium_WebDriverRepository repository.
        /// </summary>
        public static TAU_Selenium_WebDriverRepository repo = TAU_Selenium_WebDriverRepository.Instance;

        static FormValidation instance = new FormValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FormValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FormValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://automationpractice.com/index.php?controller=authentication&back=my-account' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://automationpractice.com/index.php?controller=authentication&back=my-account", "Chrome", "", false, false, false, true, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.EmailCreate' at 96;11.", repo.LoginMyStore.EmailCreateInfo, new RecordItemIndex(2));
            repo.LoginMyStore.EmailCreate.Click("96;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123{LShiftKey down}@{LShiftKey up}123111.pl' with focus on 'LoginMyStore.EmailCreate'.", repo.LoginMyStore.EmailCreateInfo, new RecordItemIndex(3));
            repo.LoginMyStore.EmailCreate.PressKeys("123{LShiftKey down}@{LShiftKey up}123111.pl");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.SpanTagCreateAnAccount' at 97;18.", repo.LoginMyStore.SpanTagCreateAnAccountInfo, new RecordItemIndex(4));
            repo.LoginMyStore.SpanTagCreateAnAccount.Click("97;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.CustomerFirstname' at 55;15.", repo.LoginMyStore.CustomerFirstnameInfo, new RecordItemIndex(5));
            repo.LoginMyStore.CustomerFirstname.Click("55;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tom' with focus on 'LoginMyStore.CustomerFirstname'.", repo.LoginMyStore.CustomerFirstnameInfo, new RecordItemIndex(6));
            repo.LoginMyStore.CustomerFirstname.PressKeys("tom");
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='customer_firstname') on item 'LoginMyStore.CustomerFirstname'.", repo.LoginMyStore.CustomerFirstnameInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.LoginMyStore.CustomerFirstnameInfo, "Id", "customer_firstname");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Type='text') on item 'LoginMyStore.CustomerFirstname'.", repo.LoginMyStore.CustomerFirstnameInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.LoginMyStore.CustomerFirstnameInfo, "Type", "text");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.CustomerLastname' at 57;12.", repo.LoginMyStore.CustomerLastnameInfo, new RecordItemIndex(9));
            repo.LoginMyStore.CustomerLastname.Click("57;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fal' with focus on 'LoginMyStore.CustomerLastname'.", repo.LoginMyStore.CustomerLastnameInfo, new RecordItemIndex(10));
            repo.LoginMyStore.CustomerLastname.PressKeys("fal");
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='customer_lastname') on item 'LoginMyStore.CustomerLastname'.", repo.LoginMyStore.CustomerLastnameInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.LoginMyStore.CustomerLastnameInfo, "Id", "customer_lastname");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Name='customer_lastname') on item 'LoginMyStore.CustomerLastname'.", repo.LoginMyStore.CustomerLastnameInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.LoginMyStore.CustomerLastnameInfo, "Name", "customer_lastname");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Type='text') on item 'LoginMyStore.CustomerLastname'.", repo.LoginMyStore.CustomerLastnameInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.LoginMyStore.CustomerLastnameInfo, "Type", "text");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.Passwd' at 59;13.", repo.LoginMyStore.PasswdInfo, new RecordItemIndex(14));
            repo.LoginMyStore.Passwd.Click("59;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123456' with focus on 'LoginMyStore.Passwd'.", repo.LoginMyStore.PasswdInfo, new RecordItemIndex(15));
            repo.LoginMyStore.Passwd.PressKeys("123456");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (data-validate>'isPasswd') on item 'LoginMyStore.Passwd'.", repo.LoginMyStore.PasswdInfo, new RecordItemIndex(16));
            Validate.AttributeContains(repo.LoginMyStore.PasswdInfo, "data-validate", "isPasswd");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.AccountCreationForm.Address1' at 77;14.", repo.LoginMyStore.AccountCreationForm.Address1Info, new RecordItemIndex(17));
            repo.LoginMyStore.AccountCreationForm.Address1.Click("77;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'oko' with focus on 'LoginMyStore.AccountCreationForm.Address1'.", repo.LoginMyStore.AccountCreationForm.Address1Info, new RecordItemIndex(18));
            repo.LoginMyStore.AccountCreationForm.Address1.PressKeys("oko");
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Name='address1') on item 'LoginMyStore.AccountCreationForm.Address1'.", repo.LoginMyStore.AccountCreationForm.Address1Info, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.LoginMyStore.AccountCreationForm.Address1Info, "Name", "address1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Type='text') on item 'LoginMyStore.AccountCreationForm.Address1'.", repo.LoginMyStore.AccountCreationForm.Address1Info, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.LoginMyStore.AccountCreationForm.Address1Info, "Type", "text");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(21));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.City' at 80;12.", repo.LoginMyStore.CityInfo, new RecordItemIndex(22));
            repo.LoginMyStore.City.Click("80;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'gda' with focus on 'LoginMyStore.City'.", repo.LoginMyStore.CityInfo, new RecordItemIndex(23));
            repo.LoginMyStore.City.PressKeys("gda");
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='city') on item 'LoginMyStore.City'.", repo.LoginMyStore.CityInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.LoginMyStore.CityInfo, "Id", "city");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Type='text') on item 'LoginMyStore.City'.", repo.LoginMyStore.CityInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.LoginMyStore.CityInfo, "Type", "text");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '17' on item 'LoginMyStore.IdState'.", repo.LoginMyStore.IdStateInfo, new RecordItemIndex(26));
            repo.LoginMyStore.IdState.Element.SetAttributeValue("TagValue", "17");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (TagValue~'1') on item 'LoginMyStore.IdState'.", repo.LoginMyStore.IdStateInfo, new RecordItemIndex(27));
            Validate.AttributeRegex(repo.LoginMyStore.IdStateInfo, "TagValue", new Regex("1"));
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.Postcode' at 96;19.", repo.LoginMyStore.PostcodeInfo, new RecordItemIndex(28));
            repo.LoginMyStore.Postcode.Click("96;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '54543' with focus on 'LoginMyStore.Postcode'.", repo.LoginMyStore.PostcodeInfo, new RecordItemIndex(29));
            repo.LoginMyStore.Postcode.PressKeys("54543");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.Postcode' at 21;17.", repo.LoginMyStore.PostcodeInfo, new RecordItemIndex(30));
            repo.LoginMyStore.Postcode.Click("21;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.AccountCreationForm.FormGroupRequiredSelect' at 340;18.", repo.LoginMyStore.AccountCreationForm.FormGroupRequiredSelectInfo, new RecordItemIndex(31));
            repo.LoginMyStore.AccountCreationForm.FormGroupRequiredSelect.Click("340;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(32));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.Phone' at 76;11.", repo.LoginMyStore.PhoneInfo, new RecordItemIndex(33));
            repo.LoginMyStore.Phone.Click("76;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.PhoneMobile' at 75;10.", repo.LoginMyStore.PhoneMobileInfo, new RecordItemIndex(34));
            repo.LoginMyStore.PhoneMobile.Click("75;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'LoginMyStore.Phone'.", repo.LoginMyStore.PhoneInfo, new RecordItemIndex(35));
            repo.LoginMyStore.Phone.PressKeys("123");
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (Type~'text') on item 'LoginMyStore.PhoneMobile'.", repo.LoginMyStore.PhoneMobileInfo, new RecordItemIndex(36));
            Validate.AttributeRegex(repo.LoginMyStore.PhoneMobileInfo, "Type", new Regex("text"));
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.AccountCreationForm.FormGroupRequired' at 401;34.", repo.LoginMyStore.AccountCreationForm.FormGroupRequiredInfo, new RecordItemIndex(37));
            repo.LoginMyStore.AccountCreationForm.FormGroupRequired.Click("401;34");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.Alias' at 165;9.", repo.LoginMyStore.AliasInfo, new RecordItemIndex(38));
            repo.LoginMyStore.Alias.Click("165;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMyStore.Register' at 56;11.", repo.LoginMyStore.RegisterInfo, new RecordItemIndex(39));
            repo.LoginMyStore.Register.Click("56;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='My account') on item 'LoginMyStore.MyAccount'.", repo.LoginMyStore.MyAccountInfo, new RecordItemIndex(40));
            Validate.AttributeEqual(repo.LoginMyStore.MyAccountInfo, "InnerText", "My account");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
