///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TAU_Selenium_WebDriver
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FormFieldValidation recording.
    /// </summary>
    [TestModule("0da12db1-debc-4381-a35d-a61e132707c6", ModuleType.Recording, 1)]
    public partial class FormFieldValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TAU_Selenium_WebDriverRepository repository.
        /// </summary>
        public static TAU_Selenium_WebDriverRepository repo = TAU_Selenium_WebDriverRepository.Instance;

        static FormFieldValidation instance = new FormFieldValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FormFieldValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FormFieldValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://bioptron-gdansk.pl/' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://bioptron-gdansk.pl/", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(1));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.ElementorElementElementorElementB35a' at 265;61.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.ElementorElementElementorElementB35aInfo, new RecordItemIndex(2));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.ElementorElementElementorElementB35a.Click("265;61");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Next}{Next}{Next}' with focus on 'BioptronZepterGdanskBioptronZepter'.", repo.BioptronZepterGdanskBioptronZepter.SelfInfo, new RecordItemIndex(3));
            repo.BioptronZepterGdanskBioptronZepter.Self.EnsureVisible();
            Keyboard.Press("{Next}{Next}{Next}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1' at 78;12.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1Info, new RecordItemIndex(4));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1.Click("78;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tomasz' with focus on 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1'.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1Info, new RecordItemIndex(5));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1.PressKeys("tomasz");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.faldrowicz{RShiftKey down}@{RShiftKey up}gmail.com{Tab}' with focus on 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1'.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1Info, new RecordItemIndex(6));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.FormFieldsField1.PressKeys(".faldrowicz{RShiftKey down}@{RShiftKey up}gmail.com{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '79221544848{Tab}subject' with focus on 'BioptronZepterGdanskBioptronZepter'.", repo.BioptronZepterGdanskBioptronZepter.SelfInfo, new RecordItemIndex(7));
            repo.BioptronZepterGdanskBioptronZepter.Self.EnsureVisible();
            Keyboard.Press("79221544848{Tab}subject");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.FormFieldMessage' at 80;13.", repo.BioptronZepterGdanskBioptronZepter.FormFieldMessageInfo, new RecordItemIndex(8));
            repo.BioptronZepterGdanskBioptronZepter.FormFieldMessage.Click("80;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'question' with focus on 'BioptronZepterGdanskBioptronZepter.FormFieldMessage'.", repo.BioptronZepterGdanskBioptronZepter.FormFieldMessageInfo, new RecordItemIndex(9));
            repo.BioptronZepterGdanskBioptronZepter.FormFieldMessage.PressKeys("question");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.Send' at 10;12.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.SendInfo, new RecordItemIndex(10));
            repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.Send.Click("10;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Wysyłanie formularza zakończone sukcesem.') on item 'BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.WysyłanieFormularzaZakończoneSukcesem'.", repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.WysyłanieFormularzaZakończoneSukcesemInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.BioptronZepterGdanskBioptronZepter.ElementorSectionWrap.WysyłanieFormularzaZakończoneSukcesemInfo, "InnerText", "Wysyłanie formularza zakończone sukcesem.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'BioptronZepterGdanskBioptronZepter'.", repo.BioptronZepterGdanskBioptronZepter.SelfInfo, new RecordItemIndex(12));
            Host.Current.CloseApplication(repo.BioptronZepterGdanskBioptronZepter.Self, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
