///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TAU_Selenium_WebDriver
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TAU_Selenium_WebDriverRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7826df47-3df0-4357-b90e-85b43d1dbcdc")]
    public partial class TAU_Selenium_WebDriverRepository : RepoGenBaseFolder
    {
        static TAU_Selenium_WebDriverRepository instance = new TAU_Selenium_WebDriverRepository();
        TAU_Selenium_WebDriverRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the TAU_Selenium_WebDriverRepository element repository.
        /// </summary>
        [RepositoryFolder("7826df47-3df0-4357-b90e-85b43d1dbcdc")]
        public static TAU_Selenium_WebDriverRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TAU_Selenium_WebDriverRepository() 
            : base("TAU_Selenium_WebDriverRepository", "/", null, 0, false, "7826df47-3df0-4357-b90e-85b43d1dbcdc", ".\\RepositoryImages\\TAU_Selenium_WebDriverRepository7826df47.rximgres")
        {
            _applicationundertest = new TAU_Selenium_WebDriverRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7826df47-3df0-4357-b90e-85b43d1dbcdc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("86865fdb-9ca9-4c6d-a803-da691c712ca9")]
        public virtual TAU_Selenium_WebDriverRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TAU_Selenium_WebDriverRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("86865fdb-9ca9-4c6d-a803-da691c712ca9")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "86865fdb-9ca9-4c6d-a803-da691c712ca9", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86865fdb-9ca9-4c6d-a803-da691c712ca9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86865fdb-9ca9-4c6d-a803-da691c712ca9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
