///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TAU_Selenium_WebDriver
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WrongEmail recording.
    /// </summary>
    [TestModule("467a4d20-c0bc-4ae8-b5b0-d790c7fd02c7", ModuleType.Recording, 1)]
    public partial class WrongEmail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TAU_Selenium_WebDriverRepository repository.
        /// </summary>
        public static TAU_Selenium_WebDriverRepository repo = TAU_Selenium_WebDriverRepository.Instance;

        static WrongEmail instance = new WrongEmail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WrongEmail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WrongEmail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://inkubit.com/en-us/#' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://inkubit.com/en-us/#", "Chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Contact' at 38;24.", repo.INKUBITMicrosoftDynamics365CRMCon.ContactInfo, new RecordItemIndex(2));
            repo.INKUBITMicrosoftDynamics365CRMCon.Contact.Click("38;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.FirstName' at 124;22.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.FirstNameInfo, new RecordItemIndex(3));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.FirstName.Click("124;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tom' with focus on 'INKUBITMicrosoftDynamics365CRMCon.Form0.FirstName'.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.FirstNameInfo, new RecordItemIndex(4));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.FirstName.PressKeys("tom");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.LastName' at 113;12.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.LastNameInfo, new RecordItemIndex(5));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.LastName.Click("113;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'falo' with focus on 'INKUBITMicrosoftDynamics365CRMCon.Form0.LastName'.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.LastNameInfo, new RecordItemIndex(6));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.LastName.PressKeys("falo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddress' at 96;22.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddressInfo, new RecordItemIndex(7));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddress.Click("96;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tom' with focus on 'INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddress'.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddressInfo, new RecordItemIndex(8));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.EmailAddress.PressKeys("tom");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.Message' at 104;30.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.MessageInfo, new RecordItemIndex(9));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.Message.Click("104;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'txt' with focus on 'INKUBITMicrosoftDynamics365CRMCon.Form0.Message'.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.MessageInfo, new RecordItemIndex(10));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.Message.PressKeys("txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'INKUBITMicrosoftDynamics365CRMCon.Form0.SEND' at 25;17.", repo.INKUBITMicrosoftDynamics365CRMCon.Form0.SENDInfo, new RecordItemIndex(11));
            repo.INKUBITMicrosoftDynamics365CRMCon.Form0.SEND.Click("25;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Email address is invalid') on item 'INKUBITMicrosoftDynamics365CRMCon.EmailAddressError'.", repo.INKUBITMicrosoftDynamics365CRMCon.EmailAddressErrorInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.INKUBITMicrosoftDynamics365CRMCon.EmailAddressErrorInfo, "InnerText", "Email address is invalid");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'INKUBITMicrosoftDynamics365CRMCon'.", repo.INKUBITMicrosoftDynamics365CRMCon.SelfInfo, new RecordItemIndex(13));
            Host.Current.KillApplication(repo.INKUBITMicrosoftDynamics365CRMCon.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
